### ISSUE TITLE
Killercoda FinOps issue

### ISSUE THREAD

**Issue by asbarbati** [krateoplatformops/krateo-lab#30]
**Describe the bug**
The playground on Killercoda "FinOps" did not function as expected during the ‘make’ command.

**To Reproduce**
1. Go to [KillerCoda FinOps](https://killercoda.com/krateoplatformops/scenario/krateo-composable-finops)
2. Click on the git clone command
3. Click on "make" command block

**Expected behavior**
Follow the instruction with copy/paste works

**Screenshots**
![finops](https://github.com/krateoplatformops/krateo/assets/122787746/09a95013-3e3b-441d-901c-010655a5954f)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox
 - Version Latest

**Additional context**
This [Makefile](https://github.com/krateoplatformops/finops-operator-exporter/blob/main/Makefile) does not contain any ‘deploy’ block.

**Comment by FrancescoL96** [comment]
This bug has been caused by an update to the Makefile in https://github.com/krateoplatformops/finops-operator-exporter/commit/e88adacd2f69b2ba554e0f49167137a3cb77acba.
The lab has been updated to use the scripts instead of the Makefile. This is a temporary solution until the repositories with the Helm chart are available.
